botany-dummy-org-1/testing1

- bugbash.md
Here is PR summary to have reviewed
> create bugbash md

- bugbash.md
> Adding to markdown

- bugbash.md
> add new page to the main site

- dave.txt
> thanks for reading

- dave.txt
> this is important

- dave.txt
> please fix this

- dave.txt
> is this fixed yet

- dave.txt
> code block

- dave.txt
> this is the best

- dave.txt
this is a change to `that one thing` to make that stuff happen
> fix the plumbing problem in the outhouse

- dave.txt
> remove some legacy tests

- dave.txt
> remove dead code

- dave.txt
> confirm previous fix

- dave.txt
> delete all tests

- dave.txt
> some cleanup

- readme.md
> this is lame

- readme.md
> another readme change

- dave.txt
> new changes to file

- readme.md
> make readme more compelling

- readme.md
> if you have time

- readme.md
contributing guide
this is v1
still needs more context
> contributing guide

- dave.txt
> remove friendly greeting

- readme.md
> local setup docs

- readme.md
> cleanup README

- readme.md
> testing guide

- readme.md
> update contributing guide

- readme.md
> add code of conduct

- readme.md
remove unused README placeholders
> remove unused README placeholders

- readme.md
> test coverage

- readme.md
> additional test coverage

- readme.md
> clean up test cases

- readme.md
> reduce test coverage

- readme.md
> more test coverage

- readme.md
> fix all the things

- readme.md
> cleanup documentation

- readme.md
> add some helpful docs

- readme.md
> increase test coverage

- readme.md
> more documentation

- readme.md
> simplify documentation

- readme.md
> remove test coverage

- readme.md
> some new change to readme

- readme.md
> cleanup readme.md

- readme.md
> contributing guide updates

- readme.md
> clean up documentation

- readme.md
> improve test coverage

- readme.md
> remove legacy docs

- readme.md
> additional tests

- readme.md
> clean up setup documentation

- readme.md
> more tests

- readme.md
> remove old tests

- readme.md
> new performance tests

- readme.md
> update performance tests

- readme.md
> new unit test documentation

- readme.md
> refactor auth

- readme.md
> login page design updates

- readme.md
> fix auth redirect error

- readme.md
new TOS page
can you take a look at this @botany-dummy-org-1/team_1
> new TOS page

- readme.md
add tests for new auth redirect
> add tests for new auth redirect

- readme.md
> new mention handler tests

- readme.md
database migration for team realationships
> database migration for team realationships

- readme.md
> fix font size on home page

- readme.md
> new favicon

- readme.md
> dockerfile optimization

- readme.md
> additional dockerfile cleanup

- readme.md
migration to drop legacy tables from db
> migration to drop legacy tables from db

- readme.md
> performance updates

- readme.md
add additional user config options
> add additional user config options

- readme.md
consistent ordering of user states
> consistent ordering of user states

- readme.md
cleanup documentation in README file
> cleanup documentation in README file

- readme.md
update tests for new email sending flow
> update tests for new email sending flow

- readme.md
> use new logo

- readme.md
> update auth flow

- readme.md
> add new user settings table

- readme.md
> add some demo features
